- type: entity
  parent: CMJumpsuitWardenCorporate
  id: JumpsuitColonySecurity
  name: security jumpsuit
  description: Standard-issue Weston-Yamada colony security uniform. It has shards of light Kevlar to help protect against stabbing weapons and bullets.