- type: job
  parent: CMJobSquadBase
  id: XenoSurvival_Colonist
  name: cm-job-name-colonist
  description: cm-job-description-colonist
  playTimeTracker: XenoSurvival_JobColonist
  startingGear: XenoSurvival_GearColonist
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  accessGroups:
  - Colonist
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      firearms: 0
    - type: RMCUserBulkyArmorIncapable
  hasIcon: false

- type: startingGear
  id: XenoSurvival_GearColonist
  equipment:
    jumpsuit: CMJumpsuitColonist
    id: XenoSurvival_IDColonist
    ears: XenoSurvival_HeadsetColony

- type: entity
  parent: XenoSurvival_HyperSleepJobSpawner
  id: XenoSurvival_HyperSleepChamberColonist
  suffix: Xeno Survival, Colonist
  components:
  - type: SpawnPoint
    job_id: XenoSurvival_Colonist

- type: playTimeTracker
  id: XenoSurvival_JobColonist
